/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;
import java.awt.BorderLayout;
import raven.dao.userDAO;
import raven.model.modelUser;
import raven.service.serviceUser;
import raven.tablemodel.tableUser;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Olla
 */
public class FormUser extends javax.swing.JPanel {
    private final tableUser tblModel = new tableUser();
    private final serviceUser servis = new userDAO();
    
    /**
     * Creates new form FormManajemenUser
     */
    public FormUser() {
        initComponents();
         loadData();
        tableUser.setModel(tblModel);
        setLebarKolom();
        
        
    }

    
         private void setLebarKolom() {
        TableColumnModel kolom = tableUser.getColumnModel();
        
        kolom.getColumn(0).setPreferredWidth(50);
        kolom.getColumn(0).setMaxWidth(50);
        kolom.getColumn(0).setMinWidth(50);
    }

    private void loadData() {
         List<modelUser> list = servis.showData();
        tblModel.setData(list);
        tblModel.fireTableDataChanged();
        tableUser.revalidate();
        tableUser.repaint();
    }
     private void tambahData() {
        InputManajemenUser input = new InputManajemenUser(null, true, 0, null, this);
        input.pack(); 
        input.setLocationRelativeTo(null); 
        input.setVisible(true);
        loadData();
    }
     private void editData() {
     int row = tableUser.getSelectedRow();
    if (row >= 0) {
        modelUser user = tblModel.getData(row);
        InputManajemenUser input = new InputManajemenUser(null, true, 1, user, this);
        input.idUserEdit = user.getIdUser();
        input.pack();
        input.setLocationRelativeTo(null); 
        input.setVisible(true);
        loadData();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit");
    }
}
    private void hapusData() {
    int selectedRow = tableUser.getSelectedRow();
    
    // Validasi apakah ada baris yang dipilih
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, 
            "Silakan pilih data yang ingin dihapus terlebih dahulu",
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Konfirmasi penghapusan
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin menghapus data ini?",
        "Konfirmasi Hapus",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Ambil ID dari baris yang dipilih (kolom pertama)
            int idUser = (int) tableUser.getValueAt(selectedRow, 1);
            
            // Panggil DAO untuk hapus data
            userDAO dao = new userDAO();
            dao.hapusData(idUser);
            
            // Refresh tabel
            loadData();
            
            // Feedback ke user
            JOptionPane.showMessageDialog(this, 
                "Data berhasil dihapus",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            // Tampilkan error detail
            JOptionPane.showMessageDialog(this, 
                "Gagal menghapus data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
       private void gantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tableUser.getSelectedRow();
        
        if (selectedRow >= 0) {
            modelUser user = tblModel.getData(selectedRow);
            InputGantiPassword dialog = new InputGantiPassword(null, true, user);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            loadData(); // Refresh jika password diganti
        } else {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih user terlebih dahulu.",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }
    }
      void refreshtable() {
        loadData();
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tambah = new javax.swing.JToggleButton();
        edit = new javax.swing.JToggleButton();
        hapus = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 64));
        jPanel1.setMinimumSize(new java.awt.Dimension(60, 64));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 64));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA USER");

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        tambahData();
    }//GEN-LAST:event_tambahActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       editData();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       hapusData();
    }//GEN-LAST:event_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton edit;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    private javax.swing.JToggleButton tambah;
    // End of variables declaration//GEN-END:variables

}
