/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import raven.dao.userDAO;
import javax.swing.*;
import java.awt.event.*;
import raven.model.modelUser;

/**s
 *
 * @author Olla
 */
public class InputGantiPassword extends javax.swing.JDialog {

    private userDAO dao = new userDAO(); 
    private modelUser user;
    /**
     * Creates new form FormGantiPassword
     */


public InputGantiPassword(java.awt.Frame parent, boolean modal, modelUser user) {
    super(parent, modal);
    this.user = user;
    initComponents(); 
    jPanel1.setPreferredSize(new Dimension(450, 550));
    pack(); // wajib agar ukuran sesuai
    setLocationRelativeTo(parent); 
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    txtUsername.setText(user.getUsername());

    
}

    
    
  public InputGantiPassword() {
    this(new javax.swing.JFrame(), true, new modelUser());
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLUsername = new javax.swing.JLabel();
        jLUsername1 = new javax.swing.JLabel();
        jLUsername3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnsimpan = new com.raven.swing.ButtonGradient();
        btnbatal = new com.raven.swing.ButtonGradient();
        txtKonfirmasiPassword = new javax.swing.JPasswordField();
        txtPasswordBaru = new javax.swing.JPasswordField();

        jPanel1.setPreferredSize(new java.awt.Dimension(389, 402));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 203, 112));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GANTI PASSWORD");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Manajemen User >Ganti Pasword  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 389, 75));

        jLUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLUsername.setText("Username");
        jPanel1.add(jLUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, 89, 23));

        jLUsername1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLUsername1.setText("Konfirmasi Password Baru");
        jPanel1.add(jLUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 22));

        jLUsername3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLUsername3.setText("Password Baru");
        jPanel1.add(jLUsername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 114, 23));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 175, -1));

        btnsimpan.setText("SIMPAN");
        btnsimpan.setColor1(new java.awt.Color(46, 204, 113));
        btnsimpan.setColor2(new java.awt.Color(46, 204, 113));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 344, 71, -1));

        btnbatal.setText("BATAL");
        btnbatal.setColor1(new java.awt.Color(46, 204, 113));
        btnbatal.setColor2(new java.awt.Color(46, 204, 113));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 344, 71, -1));

        txtKonfirmasiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKonfirmasiPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtKonfirmasiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 175, -1));

        txtPasswordBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordBaruActionPerformed(evt);
            }
        });
        jPanel1.add(txtPasswordBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 175, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
    String username = txtUsername.getText().trim();
    String passwordBaru = new String(txtPasswordBaru.getPassword()).trim();
    String konfirmasi = new String(txtKonfirmasiPassword.getPassword()).trim();

        if (username.isEmpty() || passwordBaru.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!passwordBaru.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Password baru dan konfirmasi tidak cocok!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
 if (passwordBaru.length() < 3) {
        JOptionPane.showMessageDialog(this,
            "Password minimal 3 karakter!",
            "Password Lemah",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

       boolean sukses = dao.gantiPassword(username, passwordBaru);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Password berhasil diubah!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        
            txtPasswordBaru.setText("");
            txtKonfirmasiPassword.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "username tidak ditemukan!", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        txtUsername.setText("");
        txtPasswordBaru.setText("");
        txtKonfirmasiPassword.setText("");
        this.dispose(); 
    }//GEN-LAST:event_btnbatalActionPerformed

    private void txtKonfirmasiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKonfirmasiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKonfirmasiPasswordActionPerformed

    private void txtPasswordBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordBaruActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

public static void main(String[] args) {
   SwingUtilities.invokeLater(() -> {
        new InputGantiPassword().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ButtonGradient btnbatal;
    private com.raven.swing.ButtonGradient btnsimpan;
    private javax.swing.JLabel jLUsername;
    private javax.swing.JLabel jLUsername1;
    private javax.swing.JLabel jLUsername3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtKonfirmasiPassword;
    private javax.swing.JPasswordField txtPasswordBaru;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}

